// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/jdr299zdh5cew256ans96/EtaLexer.flex

/*
 * THIS IS THE USER CODE SECTION
 *
 * UserCode
 *
 * Options and declarations
 *
 * Lexical rules
 */
package main.java.jdr299zdh5cew256ans96;

import main.java.jdr299zdh5cew256ans96.lexertokens.*;
import main.java.jdr299zdh5cew256ans96.cup.sym;
import java_cup.runtime.Symbol;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class EtaLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int MULTILINECOMMENT = 4;
  public static final int STRINGLIT = 6;
  public static final int CHARACTER = 8;
  public static final int ERROR = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\2\22\0\1\1"+
    "\1\5\1\6\2\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\11\23"+
    "\1\24\1\25\1\26\1\27\1\30\2\0\6\31\24\32"+
    "\1\33\1\34\1\35\1\0\1\36\1\0\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\32\1\45\1\46\1\32"+
    "\1\47\1\50\1\32\1\51\1\52\2\32\1\53\1\54"+
    "\1\55\1\56\1\32\1\57\1\60\2\32\1\61\1\62"+
    "\1\63\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\4\0\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\2\1\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\3\1\32\12\30\1\33\1\34"+
    "\1\35\1\36\1\4\1\36\1\37\1\40\1\41\2\37"+
    "\1\42\1\43\1\44\2\42\1\2\1\45\1\46\1\47"+
    "\1\0\1\50\1\51\3\0\1\52\1\53\1\54\4\30"+
    "\1\55\6\30\1\40\1\0\1\56\1\57\1\56\1\60"+
    "\1\61\2\60\1\62\1\63\2\0\4\30\1\64\4\30"+
    "\1\65\1\30\1\0\2\60\1\66\2\0\1\67\1\30"+
    "\1\70\1\30\1\71\2\30\1\72\1\30\1\0\1\60"+
    "\1\0\1\73\1\0\1\74\1\75\1\76\2\30\1\77"+
    "\1\0\1\100\2\60\2\0\1\101\1\102\1\0\1\60"+
    "\1\103\3\0\1\60\3\0\1\60\3\0\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\u016c"+
    "\0\u0138\0\u01a0\0\u01d4\0\u0138\0\u0138\0\u0208\0\u0138\0\u0138"+
    "\0\u023c\0\u0138\0\u0138\0\u0138\0\u0138\0\u0270\0\u02a4\0\u02d8"+
    "\0\u0138\0\u0138\0\u030c\0\u0340\0\u0374\0\u03a8\0\u0138\0\u03dc"+
    "\0\u0138\0\u0138\0\u0410\0\u0444\0\u0478\0\u04ac\0\u04e0\0\u0514"+
    "\0\u0548\0\u057c\0\u05b0\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138"+
    "\0\u05e4\0\u0138\0\u0618\0\u0138\0\u064c\0\u0680\0\u06b4\0\u06e8"+
    "\0\u071c\0\u0750\0\u0784\0\u0138\0\u0138\0\u0138\0\u0138\0\u07b8"+
    "\0\u0138\0\u0138\0\u07ec\0\u0820\0\u0854\0\u0138\0\u0138\0\u0138"+
    "\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u03a8\0\u0958\0\u098c\0\u09c0"+
    "\0\u09f4\0\u0a28\0\u0a5c\0\u0138\0\u0a90\0\u0138\0\u0138\0\u0a90"+
    "\0\u0ac4\0\u0138\0\u0af8\0\u0b2c\0\u0b60\0\u0138\0\u0b94\0\u0bc8"+
    "\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u03a8\0\u0ccc\0\u0d00\0\u0d34"+
    "\0\u0d68\0\u03a8\0\u0d9c\0\u0dd0\0\u0138\0\u0e04\0\u0138\0\u0e38"+
    "\0\u0e6c\0\u03a8\0\u0ea0\0\u03a8\0\u0ed4\0\u03a8\0\u0f08\0\u0f3c"+
    "\0\u03a8\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\u0138\0\u1040\0\u0138"+
    "\0\u03a8\0\u03a8\0\u1074\0\u10a8\0\u03a8\0\u10dc\0\u0138\0\u1110"+
    "\0\u1144\0\u1178\0\u11ac\0\u03a8\0\u03a8\0\u11e0\0\u1214\0\u0138"+
    "\0\u1248\0\u127c\0\u12b0\0\u12e4\0\u1318\0\u134c\0\u1380\0\u13b4"+
    "\0\u13e8\0\u141c\0\u1450\0\u1484";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\2\10\1\11\1\10\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\2\36\1\37\1\40\1\41\1\42\1\36\1\43\2\36"+
    "\1\44\1\45\1\36\1\46\2\36\1\47\1\36\1\50"+
    "\1\36\1\51\1\52\1\53\1\36\1\54\1\55\1\56"+
    "\2\57\1\60\75\57\1\61\47\57\2\62\1\63\3\62"+
    "\1\64\13\62\1\65\11\62\1\66\27\62\2\67\1\70"+
    "\6\67\1\71\10\67\1\72\11\67\1\73\27\67\2\74"+
    "\3\11\57\74\65\0\2\10\1\0\1\10\106\0\1\75"+
    "\42\0\1\76\66\0\1\77\102\0\1\100\47\0\1\101"+
    "\4\0\1\102\64\0\1\103\1\30\32\0\1\104\1\0"+
    "\1\105\25\0\2\30\67\0\1\106\63\0\1\107\63\0"+
    "\1\110\45\0\1\36\10\0\2\36\5\0\2\36\3\0"+
    "\23\36\61\0\1\104\1\0\1\105\14\0\1\36\10\0"+
    "\2\36\5\0\2\36\3\0\14\36\1\111\1\112\5\36"+
    "\14\0\1\36\10\0\2\36\5\0\2\36\3\0\12\36"+
    "\1\113\10\36\14\0\1\36\10\0\2\36\5\0\2\36"+
    "\3\0\1\36\1\114\21\36\14\0\1\36\10\0\2\36"+
    "\5\0\2\36\3\0\6\36\1\115\4\36\1\116\7\36"+
    "\14\0\1\36\10\0\2\36\5\0\2\36\3\0\20\36"+
    "\1\117\2\36\14\0\1\36\10\0\2\36\5\0\2\36"+
    "\3\0\5\36\1\120\15\36\14\0\1\36\10\0\2\36"+
    "\5\0\2\36\3\0\15\36\1\121\5\36\14\0\1\36"+
    "\10\0\2\36\5\0\2\36\3\0\16\36\1\122\4\36"+
    "\14\0\1\36\10\0\2\36\5\0\2\36\3\0\7\36"+
    "\1\123\13\36\24\0\1\60\42\0\6\63\1\124\55\63"+
    "\56\0\1\125\1\0\1\125\3\0\6\126\1\127\2\126"+
    "\1\127\22\126\1\127\7\126\1\127\4\126\1\127\1\126"+
    "\1\127\1\126\1\127\1\130\1\126\1\130\3\126\11\131"+
    "\1\132\63\131\1\0\52\131\11\0\1\132\52\0\11\131"+
    "\1\132\44\131\1\133\1\131\1\133\11\131\1\134\2\131"+
    "\1\135\22\131\1\134\21\131\1\133\1\131\1\133\3\131"+
    "\30\0\1\136\55\0\1\103\1\30\121\0\1\137\63\0"+
    "\1\140\13\0\1\36\10\0\2\36\5\0\2\36\3\0"+
    "\14\36\1\141\6\36\14\0\1\36\10\0\2\36\5\0"+
    "\2\36\3\0\5\36\1\142\15\36\14\0\1\36\10\0"+
    "\2\36\5\0\2\36\3\0\16\36\1\143\4\36\14\0"+
    "\1\36\10\0\2\36\5\0\2\36\3\0\12\36\1\144"+
    "\10\36\14\0\1\36\10\0\2\36\5\0\2\36\3\0"+
    "\17\36\1\145\3\36\14\0\1\36\10\0\2\36\5\0"+
    "\2\36\3\0\12\36\1\146\10\36\14\0\1\36\10\0"+
    "\2\36\5\0\2\36\3\0\3\36\1\147\13\36\1\150"+
    "\3\36\14\0\1\36\10\0\2\36\5\0\2\36\3\0"+
    "\20\36\1\151\2\36\14\0\1\36\10\0\2\36\5\0"+
    "\2\36\3\0\5\36\1\152\15\36\14\0\1\36\10\0"+
    "\2\36\5\0\2\36\3\0\10\36\1\153\12\36\64\0"+
    "\1\154\2\0\11\131\1\155\63\131\1\155\47\131\1\156"+
    "\13\131\1\157\52\131\11\0\1\157\74\0\2\160\5\0"+
    "\1\160\5\0\6\160\41\0\2\161\5\0\1\161\5\0"+
    "\6\161\30\0\1\36\10\0\2\36\5\0\2\36\3\0"+
    "\12\36\1\162\10\36\14\0\1\36\10\0\2\36\5\0"+
    "\2\36\3\0\1\36\1\163\21\36\14\0\1\36\10\0"+
    "\2\36\5\0\2\36\3\0\5\36\1\164\15\36\14\0"+
    "\1\36\10\0\2\36\5\0\2\36\3\0\16\36\1\165"+
    "\4\36\14\0\1\36\10\0\2\36\5\0\2\36\3\0"+
    "\12\36\1\166\10\36\14\0\1\36\10\0\2\36\5\0"+
    "\2\36\3\0\14\36\1\167\6\36\14\0\1\36\10\0"+
    "\2\36\5\0\2\36\3\0\20\36\1\170\2\36\14\0"+
    "\1\36\10\0\2\36\5\0\2\36\3\0\5\36\1\171"+
    "\15\36\14\0\1\36\10\0\2\36\5\0\2\36\3\0"+
    "\12\36\1\172\10\36\25\0\2\173\5\0\1\173\5\0"+
    "\6\173\17\0\11\131\1\155\10\131\2\174\5\131\1\174"+
    "\5\131\6\174\17\131\22\0\2\175\5\0\1\175\5\0"+
    "\6\175\16\0\1\176\22\0\2\177\5\0\1\177\5\0"+
    "\6\177\16\0\1\200\11\0\1\36\10\0\2\36\5\0"+
    "\2\36\3\0\11\36\1\201\11\36\14\0\1\36\10\0"+
    "\2\36\5\0\2\36\3\0\5\36\1\202\15\36\14\0"+
    "\1\36\10\0\2\36\5\0\2\36\3\0\15\36\1\203"+
    "\5\36\14\0\1\36\10\0\2\36\5\0\2\36\3\0"+
    "\15\36\1\204\5\36\14\0\1\36\10\0\2\36\5\0"+
    "\2\36\3\0\5\36\1\205\15\36\25\0\2\206\5\0"+
    "\1\206\5\0\6\206\16\0\1\207\11\131\1\155\10\131"+
    "\2\210\5\131\1\210\5\131\6\210\16\131\1\211\22\0"+
    "\2\212\5\0\1\212\5\0\6\212\16\0\1\176\22\0"+
    "\2\213\5\0\1\213\5\0\6\213\16\0\1\200\11\0"+
    "\1\36\10\0\2\36\5\0\2\36\3\0\4\36\1\214"+
    "\16\36\14\0\1\36\10\0\2\36\5\0\2\36\3\0"+
    "\13\36\1\215\7\36\25\0\2\216\5\0\1\216\5\0"+
    "\6\216\16\0\1\207\11\131\1\155\10\131\2\217\5\131"+
    "\1\217\5\131\6\217\16\131\1\211\11\131\1\220\52\131"+
    "\22\0\2\221\5\0\1\221\5\0\6\221\16\0\1\176"+
    "\22\0\2\222\5\0\1\222\5\0\6\222\16\0\1\200"+
    "\22\0\2\223\5\0\1\223\5\0\6\223\16\0\1\207"+
    "\11\131\1\155\10\131\2\224\5\131\1\224\5\131\6\224"+
    "\16\131\1\211\22\0\2\225\5\0\1\225\5\0\6\225"+
    "\16\0\1\176\22\0\2\226\5\0\1\226\5\0\6\226"+
    "\16\0\1\200\22\0\2\227\5\0\1\227\5\0\6\227"+
    "\16\0\1\207\11\131\1\155\10\131\2\230\5\131\1\230"+
    "\5\131\6\230\16\131\1\211\22\0\2\231\5\0\1\231"+
    "\5\0\6\231\16\0\1\176\22\0\2\232\5\0\1\232"+
    "\5\0\6\232\16\0\1\200\22\0\2\233\5\0\1\233"+
    "\5\0\6\233\16\0\1\207\11\131\1\155\10\131\2\234"+
    "\5\131\1\234\5\131\6\234\16\131\1\211\63\0\1\176"+
    "\63\0\1\200\63\0\1\207\11\131\1\155\51\131\1\211";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5304];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\4\0\1\1\1\11\1\1\1\11\2\1\2\11"+
    "\1\1\2\11\1\1\4\11\3\1\2\11\4\1\1\11"+
    "\1\1\2\11\11\1\5\11\1\1\1\11\1\1\1\11"+
    "\7\1\4\11\1\0\2\11\3\0\3\11\13\1\1\11"+
    "\1\0\2\11\2\1\1\11\3\1\1\11\2\0\13\1"+
    "\1\0\1\11\1\1\1\11\2\0\11\1\1\0\1\1"+
    "\1\0\1\11\1\0\1\11\5\1\1\0\1\11\2\1"+
    "\2\0\2\1\1\0\1\1\1\11\3\0\1\1\3\0"+
    "\1\1\3\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // string holds the stream of chars following a "
    StringBuffer string = new StringBuffer();  

    // Holds column number of a ' or "  or (/*)
    public int startCol;

    // Holds line number of a ' or " (/*)
    public int startLine;

    // errorCode is updated when a lexing error is scanned
    public EtaError.ERROR_CODE errorCode = EtaError.ERROR_CODE.NO_ERROR;

    /* Returns a new java_cup.runtime.Symbol object
     * 
     * Parameters: type corresponds to one of the terminal symbol values in sym.java
     *
     * Precondition: type is a valid .sym value
     *               token is a valid EtaToken class object
     *
     * Postcondition: a new Symbol object is returned with correct: .sym value, EtaToken type,
     *                column number, and line number
    */
    private Symbol symbol(int type, EtaToken token) {
      if (type == sym.STRING_LITERAL || type == sym.CHARACTER_LITERAL
      || (type == sym.ERROR
      && (errorCode == EtaError.ERROR_CODE.CHAR_ERROR
      || errorCode == EtaError.ERROR_CODE.UNMATCHED_CHAR_ERROR
      || errorCode == EtaError.ERROR_CODE.UNMATCHED_STRING_ERROR
      || errorCode == EtaError.ERROR_CODE.STRING_ERROR
      || errorCode == EtaError.ERROR_CODE.COMMENT_UNCLOSED
      || errorCode == EtaError.ERROR_CODE.INVALID_ESCAPE
      || errorCode == EtaError.ERROR_CODE.TOKEN_NOT_FOUND_ERROR))) {
        token.setCol(startCol);
        token.setLine(startLine);
      } else {
        token.setCol(yycolumn+1);
        token.setLine(yyline+1);
      }
      if (type == sym.STRING_LITERAL) {
        // Clear buffer
        string.delete(0,string.length());
      }
      return new Symbol(type, token);
    }

    // Returns yyline + 1 (yyline starts at 0) 
    public int lineNumber() { return yyline + 1; }
    
    // Returns yycolumn + 1 (yycolumn starts at 0)
    public int column() { return yycolumn + 1; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public EtaLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(sym.EOF, new EtaEOF());
            }  // fall though
            case 157: break;
            case MULTILINECOMMENT: {
              errorCode = EtaError.ERROR_CODE.COMMENT_UNCLOSED; 
                                        return symbol(sym.ERROR, new EtaError(errorCode));
            }  // fall though
            case 158: break;
            case STRINGLIT: {
              errorCode = EtaError.ERROR_CODE.UNMATCHED_STRING_ERROR; 
                                        return symbol(sym.ERROR, new EtaError(errorCode));
            }  // fall though
            case 159: break;
            case CHARACTER: {
              errorCode = EtaError.ERROR_CODE.UNMATCHED_CHAR_ERROR; 
                                        return symbol(sym.ERROR, new EtaError(errorCode));
            }  // fall though
            case 160: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return symbol(sym.INTEGER_LITERAL, new EtaIntLiteral(yytext()));
            }
            // fall through
          case 68: break;
          case 2:
            { return symbol(sym.ERROR, new EtaError(errorCode));
            }
            // fall through
          case 69: break;
          case 3:
            { startCol=yycolumn+1;
                                        startLine=yyline+1;
                                        errorCode = EtaError.ERROR_CODE.TOKEN_NOT_FOUND_ERROR; 
                                        yybegin(ERROR);
            }
            // fall through
          case 70: break;
          case 4:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 71: break;
          case 5:
            { System.out.print(yytext());
            }
            // fall through
          case 72: break;
          case 6:
            { return symbol(sym.NOT, new EtaNOT());
            }
            // fall through
          case 73: break;
          case 7:
            { startCol=yycolumn+1; startLine=yyline+1; yybegin(STRINGLIT);
            }
            // fall through
          case 74: break;
          case 8:
            { return symbol(sym.MODULO, new EtaModulo());
            }
            // fall through
          case 75: break;
          case 9:
            { return symbol(sym.AND, new EtaAND());
            }
            // fall through
          case 76: break;
          case 10:
            { startCol=yycolumn+1; startLine=yyline+1; yybegin(CHARACTER);
            }
            // fall through
          case 77: break;
          case 11:
            { return symbol(sym.OPEN_PAREN, new EtaOpenParen());
            }
            // fall through
          case 78: break;
          case 12:
            { return symbol(sym.CLOSE_PAREN, new EtaCloseParen());
            }
            // fall through
          case 79: break;
          case 13:
            { return symbol(sym.TIMES, new EtaMultiplication());
            }
            // fall through
          case 80: break;
          case 14:
            { return symbol(sym.PLUS, new EtaPlus());
            }
            // fall through
          case 81: break;
          case 15:
            { return symbol(sym.COMMA, new EtaComma());
            }
            // fall through
          case 82: break;
          case 16:
            { return symbol(sym.MINUS, new EtaMinus());
            }
            // fall through
          case 83: break;
          case 17:
            { return symbol(sym.DOT, new EtaDot());
            }
            // fall through
          case 84: break;
          case 18:
            { return symbol(sym.DIVIDE, new EtaDivision());
            }
            // fall through
          case 85: break;
          case 19:
            { return symbol(sym.COLON, new EtaColon());
            }
            // fall through
          case 86: break;
          case 20:
            { return symbol(sym.SEMICOLON, new EtaSemicolon());
            }
            // fall through
          case 87: break;
          case 21:
            { return symbol(sym.LT, new EtaLT());
            }
            // fall through
          case 88: break;
          case 22:
            { return symbol(sym.ASSIGN, new EtaAssign());
            }
            // fall through
          case 89: break;
          case 23:
            { return symbol(sym.GT, new EtaGT());
            }
            // fall through
          case 90: break;
          case 24:
            { return symbol(sym.IDENTIFIER, new EtaIdentifier(yytext()));
            }
            // fall through
          case 91: break;
          case 25:
            { return symbol(sym.OPEN_BRACKET, new EtaOpenBracket());
            }
            // fall through
          case 92: break;
          case 26:
            { return symbol(sym.CLOSE_BRACKET, new EtaCloseBracket());
            }
            // fall through
          case 93: break;
          case 27:
            { return symbol(sym.OPEN_BRACE, new EtaOpenBrace());
            }
            // fall through
          case 94: break;
          case 28:
            { return symbol(sym.OR, new EtaOR());
            }
            // fall through
          case 95: break;
          case 29:
            { return symbol(sym.CLOSE_BRACE, new EtaCloseBrace());
            }
            // fall through
          case 96: break;
          case 30:
            { /*Do Nothing*/
            }
            // fall through
          case 97: break;
          case 31:
            { // Test each incoming char to see if it is an ASCII or not 
                                        int unicodeVal = Integer.valueOf(Integer.parseInt(yytext().codePoints().mapToObj(Integer::toHexString).findFirst().get(),16));

                                        // Normal text
                                        if (unicodeVal < 128) {
                                          string.append(yytext());   
                                        } 
                                        // Non-ASCII Unicode
                                        else {
                                          String escapedUni = "\\x{"+Integer.toHexString(unicodeVal)+"}";
                                          string.append(escapedUni);
                                        }
            }
            // fall through
          case 98: break;
          case 32:
            { if (yytext().indexOf('\"') == -1) {
                                            errorCode = EtaError.ERROR_CODE.UNMATCHED_STRING_ERROR; 
                                        } else {
                                            errorCode = EtaError.ERROR_CODE.STRING_ERROR;
                                        }
                                            return symbol(sym.ERROR, new EtaError(errorCode));
            }
            // fall through
          case 99: break;
          case 33:
            { yybegin(YYINITIAL); 
                                        String result = string.toString();  // Store result in String before buffer is cleared
                                        return symbol(sym.STRING_LITERAL, new EtaStrLiteral(result));
            }
            // fall through
          case 100: break;
          case 34:
            { errorCode = EtaError.ERROR_CODE.UNMATCHED_CHAR_ERROR; 
                                        return symbol(sym.ERROR, new EtaError(errorCode));
            }
            // fall through
          case 101: break;
          case 35:
            { errorCode = EtaError.ERROR_CODE.CHAR_ERROR; yybegin(ERROR);
            }
            // fall through
          case 102: break;
          case 36:
            { yybegin(ERROR); errorCode = EtaError.ERROR_CODE.CHAR_ERROR;
            }
            // fall through
          case 103: break;
          case 37:
            { return symbol(sym.NOT_EQUAL, new EtaNotEquals());
            }
            // fall through
          case 104: break;
          case 38:
            { startCol=yycolumn+1;
                                        startLine=yyline+1; 
                                        return symbol(sym.STRING_LITERAL, new EtaStrLiteral(""));
            }
            // fall through
          case 105: break;
          case 39:
            { startCol=yycolumn+1;
                                        startLine=yyline+1; 
                                        errorCode = EtaError.ERROR_CODE.CHAR_ERROR; yybegin(ERROR);
                                        return symbol(sym.ERROR, new EtaError(errorCode));
            }
            // fall through
          case 106: break;
          case 40:
            { startCol=yycolumn+1; startLine=yyline+1; yybegin(MULTILINECOMMENT);
            }
            // fall through
          case 107: break;
          case 41:
            { yybegin(COMMENT);
            }
            // fall through
          case 108: break;
          case 42:
            { return symbol(sym.LEQ, new EtaLEQ());
            }
            // fall through
          case 109: break;
          case 43:
            { return symbol(sym.EQUALS, new EtaEquals());
            }
            // fall through
          case 110: break;
          case 44:
            { return symbol(sym.GEQ, new EtaGEQ());
            }
            // fall through
          case 111: break;
          case 45:
            { return symbol(sym.IF, new EtaIf());
            }
            // fall through
          case 112: break;
          case 46:
            { errorCode = EtaError.ERROR_CODE.INVALID_ESCAPE; yybegin(ERROR);
            }
            // fall through
          case 113: break;
          case 47:
            { string.append(yytext());
            }
            // fall through
          case 114: break;
          case 48:
            { if (yytext().indexOf('\'') == -1) {
                                            errorCode = EtaError.ERROR_CODE.UNMATCHED_CHAR_ERROR; 
                                        } else {
                                            errorCode = EtaError.ERROR_CODE.CHAR_ERROR; 
                                        }
                                        return symbol(sym.ERROR, new EtaError(errorCode));
            }
            // fall through
          case 115: break;
          case 49:
            { // Test each incoming char to see if it is an ASCII or not
                                        String text = yytext().substring(0,yytext().length()-1);      // remove ending '
                                        int unicodeVal = Integer.valueOf(Integer.parseInt(text.codePoints().mapToObj(Integer::toHexString).findFirst().get(),16));

                                        // Normal text
                                        if (unicodeVal < 128) {
                                          yybegin(YYINITIAL);
                                          return symbol(sym.CHARACTER_LITERAL, new EtaCharacterLiteral(text));   
                                        } 
                                        // Non-ASCII Unicode
                                        else {
                                          String escapedUni = "\\x{"+Integer.toHexString(unicodeVal)+"}";
                                          yybegin(YYINITIAL);
                                          return symbol(sym.CHARACTER_LITERAL, new EtaCharacterLiteral(escapedUni));
                                        }
            }
            // fall through
          case 116: break;
          case 50:
            { errorCode = EtaError.ERROR_CODE.UNMATCHED_CHAR_ERROR; 
                                        yybegin(ERROR);
            }
            // fall through
          case 117: break;
          case 51:
            { return symbol(sym.HIGH_MULT, new EtaHighMultiplication());
            }
            // fall through
          case 118: break;
          case 52:
            { return symbol(sym.INT, new EtaInt());
            }
            // fall through
          case 119: break;
          case 53:
            { return symbol(sym.USE, new EtaUse());
            }
            // fall through
          case 120: break;
          case 54:
            { String charVal = String.valueOf(yytext().substring(0,2));
                                        yybegin(YYINITIAL);
                                        return symbol(sym.CHARACTER_LITERAL, new EtaCharacterLiteral(charVal));
            }
            // fall through
          case 121: break;
          case 55:
            { return symbol(sym.BOOL, new EtaBool());
            }
            // fall through
          case 122: break;
          case 56:
            { return symbol(sym.ELSE, new EtaElse());
            }
            // fall through
          case 123: break;
          case 57:
            { if (HelperCli.isRho) {
                                            	return symbol(sym.NULL, new RhoNull());
                                            }

                                            return symbol(sym.IDENTIFIER, new EtaIdentifier(yytext()));
            }
            // fall through
          case 124: break;
          case 58:
            { return symbol(sym.TRUE, new EtaTrue());
            }
            // fall through
          case 125: break;
          case 59:
            { int dec = Integer.parseInt(yytext().substring(3,yytext().length()-1));
                                        return symbol(sym.INTEGER_LITERAL, new EtaIntLiteral(""+dec));
            }
            // fall through
          case 126: break;
          case 60:
            { int dec = Integer.parseInt(yytext().substring(3,yytext().length()-1), 16);
                                        return symbol(sym.INTEGER_LITERAL, new EtaIntLiteral(""+dec));
            }
            // fall through
          case 127: break;
          case 61:
            { if (HelperCli.isRho) {
      	                                    	return symbol(sym.BREAK, new RhoBreak());
      	                                    }

      	                                    return symbol(sym.IDENTIFIER, new EtaIdentifier(yytext()));
            }
            // fall through
          case 128: break;
          case 62:
            { return symbol(sym.FALSE, new EtaFalse());
            }
            // fall through
          case 129: break;
          case 63:
            { return symbol(sym.WHILE, new EtaWhile());
            }
            // fall through
          case 130: break;
          case 64:
            { int dec = Integer.parseInt(yytext().substring(3,yytext().length()-1), 16);
                                        if (dec >= 32 && dec <= 126) {
                                           String asciiRepresentation = String.valueOf((char)dec);
                                           string.append(asciiRepresentation);
                                           } else {
                                           string.append(yytext());
                                         }
            }
            // fall through
          case 131: break;
          case 65:
            { if (HelperCli.isRho) {
      	                                        return symbol(sym.RECORD, new RhoRecord());
      	                                    }

      	                                    return symbol(sym.IDENTIFIER, new EtaIdentifier(yytext()));
            }
            // fall through
          case 132: break;
          case 66:
            { return symbol(sym.RETURN, new EtaReturn());
            }
            // fall through
          case 133: break;
          case 67:
            { int dec = Integer.parseInt(yytext().substring(3,yytext().length()-2), 16);
                                        if (dec >= 32 && dec <= 126) {
                                          String asciiRepresentation = String.valueOf((char)dec);
                                          yybegin(YYINITIAL);
                                          return symbol(sym.CHARACTER_LITERAL, new EtaCharacterLiteral(asciiRepresentation));
                                        } else {
                                            yybegin(YYINITIAL);
                                            return symbol(sym.CHARACTER_LITERAL, new EtaCharacterLiteral(yytext()));
                                        }
            }
            // fall through
          case 134: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java EtaLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        EtaLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new EtaLexer(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
